name = "gpxb"
version = "1.1.0"
description = "A tiny GPX builder for Gleam"
licences = ["Apache-2.0"]

repository = { type = "github", user = "lpil", repo = "gpxb" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.45.0 and < 2.0.0"
xmb = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.1.8 and < 2.0.0"
